apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websajtikaingress
  annotations:     
    cert-manager.io/issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - programerika.com
      - www.programerika.com
      secretName: websajtika-prod-tls
  rules:
  - host: www.programerika.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: websajtika
            port:
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: webgejmikaback
            port:
              number: 8080
  - host: programerika.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: websajtika
            port:
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: webgejmikaback
            port:
              number: 8080