apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websajtikaingress
spec:
  ingressClassName: nginx
  rules:
  - host: programerika.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: websajtika
            port:
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: webgejmikaback
            port:
              number: 8080